Ignoring exception in command play:
Traceback (most recent call last):
  File "/home/ghaith/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 167, in wrapped
    ret = await coro(*args, **kwargs)
  File "/mnt/c/users/ghaith/documents/fun_coding/music_discord/musicbot/music.py", line 124, in play
    s = format['url'].removeprefix('https://')
AttributeError: 'str' object has no attribute 'removeprefix'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ghaith/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 994, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ghaith/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 894, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/ghaith/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 176, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'str' object has no attribute 'removeprefix'
Ignoring exception in command play:
Traceback (most recent call last):
  File "/home/ghaith/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 167, in wrapped
    ret = await coro(*args, **kwargs)
  File "/mnt/c/users/ghaith/documents/fun_coding/music_discord/musicbot/music.py", line 124, in play
    s = format['url'].removeprefix('https://')
AttributeError: 'str' object has no attribute 'removeprefix'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ghaith/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 994, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ghaith/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 894, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/ghaith/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 176, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'str' object has no attribute 'removeprefix'
The Weeknd - After Hours (Audio)
The Weeknd - After Hours (Audio)
[libopus @ 0x7ffff50e4ec0] Queue input is backward in time
[opus @ 0x7ffff52f7000] Non-monotonous DTS in output stream 0:0; previous: 479688, current: 479307; changing to 479689. This may result in incorrect timestamps in the output file.
[libopus @ 0x7fffdba22ec0] Queue input is backward in time
[opus @ 0x7fffdbc35000] Non-monotonous DTS in output stream 0:0; previous: 479688, current: 479307; changing to 479689. This may result in incorrect timestamps in the output file.
[tls @ 0x7fffdba7a3c0] Error in the pull function.
[https @ 0x7fffdb93d280] Will reconnect at 720896 in 0 second(s), error=Input/output error.
Traceback (most recent call last):
  File "/home/ghaith/.local/lib/python3.8/site-packages/discord/player.py", line 686, in _call_after
    self.after(error)
  File "/mnt/c/users/ghaith/documents/fun_coding/music_discord/musicbot/music.py", line 83, in <lambda>
    ctx.voice_client.play(source, after= lambda x : self.play_next(ctx))
  File "/mnt/c/users/ghaith/documents/fun_coding/music_discord/musicbot/music.py", line 83, in play_next
    ctx.voice_client.play(source, after= lambda x : self.play_next(ctx))
AttributeError: 'NoneType' object has no attribute 'play'
The Weeknd - After Hours (Audio)
Cry Baby
